# Generated by Django 3.1.1 on 2020-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
