# Generated by Django 3.1.1 on 2020-10-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
